function [ ] = display_plots( reconstruction_error, trueplot, only_x )
%   display_plots ( reconstruction_error, trueplot, only_x)
%   This function plots the true trajectory of the animal and the reconstructed
%   trajectory overlayed over it. The red line represents the true trajectory while
%   the blue line represents the reconstructed trajectory. The function plots
%   only one coordinate at a time.
%
%  INPUT
%   reconstruction_error       - This object contains the details of the error of reconstruction,
%                                and is generated by the recon_error function.
%
%  Optional INPUT
%   trueplot                   - This option enables plotting using true units, instead of grid cell
%                                units. By default, it is set to 0. When enabled, it calculates
%                                the position of the reconstructed grid cell by estimating the center
%                                of the cell.
%   only_x                     - This parameter enables plotting of Y-coordinate as well. By default,
%                                it is set to 0. The function can only plot one coordinate at a time,
%                                and so the Y-coordinate plot must be triggered by any key press.

if(nargin<1)
    error('Please provide a reconstructed trajectory');
elseif(nargin<2)
    trueplot=0;
    only_x=1;
elseif(nargin<3)
    only_x=1;
end


if(iscell(reconstruction_error))
    reconstruction_error=reconstruction_error{1};
end


if(trueplot==0)
    plot(reconstruction_error(:,1),reconstruction_error(:,2),'color','red','LineWidth',2);
    hold on;
    plot(reconstruction_error(:,1),reconstruction_error(:,4));
    hold off;
    if(only_x==0)
        waitforbuttonpress;
        plot(reconstruction_error(:,1),reconstruction_error(:,3),'color','red','LineWidth',2);
        hold on;
        plot(reconstruction_error(:,1),reconstruction_error(:,5));
        hold off;
    end
    
else
    plot(reconstruction_error(:,1),reconstruction_error(:,7),'color','red','LineWidth',2);
    hold on;
    plot(reconstruction_error(:,1),reconstruction_error(:,9));
    hold off;
    if(only_x==0)
        waitforbuttonpress
        plot(reconstruction_error(:,1),reconstruction_error(:,8),'color','red','LineWidth',2);
        hold on;
        plot(reconstruction_error(:,1),reconstruction_error(:,10));
        hold off;
    end
end


% waitforbuttonpress;
% plot(reconstruction_error(:,1),reconstruction_error(:,5),'color','red','LineWidth',2);
% hold on;
% plot(reconstruction_error(:,1),reconstruction_error(:,3));
% hold off;
% waitforbuttonpress;
% hist(reconstruction_error(:,6));

end

