function [ ] = display_neuronselectivity( params, checker)
%display_neuronselectivity(model_params, checker)
%   Displays the maze with every location marked with the most selective neuron.
%	This is calculated by finding the neuron with the greatest firing rate to 
%	total firing rate ratio, for every location. This provides a way to visualize
%	different place fields across the maze.
%
% 	Input -
% model_params  - Cell array containing parameters such as firing rates and
%                 occupancy matrices. This object is generated by the training
%                 method, given the spiking and positinal data.
%
% Optional inputs
%   checker		- If set to 1, will display the result in a checkered grid.
% 				  By defualt, it is set to 0.
if(nargin<1)
    error('Call function with parameter model and neuron number.');
end

if(nargin==1)
    checker=1;
end

neurons=params{1}(1);
gridmax_x=params{1}(2);
gridmax_y=params{1}(3);
firingrates=params{4};

selectivity_grid=zeros(gridmax_x,gridmax_y);

for x=1:gridmax_x
	for y=1:gridmax_y
		max_rate=0;
		max_n=0;
		for tt=1:neurons
			sumrates=sum(sum(firingrates{tt}));
			selectivity= firingrates{tt}(x,y)/sumrates;
			if(selectivity>max_rate)
				max_rate=selectivity;
				max_n=tt;
			end
		end
		selectivity_grid(x,y)=max_n;
		if(selectivity_grid(x,y)==0)
			selectivity_grid(x,y)=-1;
		end

	end
end

map=rot90(selectivity_grid);
if(checker==1)
    pcolor(flipud(map));
else
    imagesc(map);
end

title('Neuron selectivity map');
xlabel('X (grid units)');
ylabel('Y (grid units)');
c=colorbar;
ylabel(c,'Neuron number');


end

